### PR TITLE
feat(cli-preview): implement prepare dev env stage

### PR DESCRIPTION
**Pull request by kuojianlu**
Happy path:
image

Error path:
image

### CODE REVIEW

**Comment by swatDong** [comment]
> Happy path:
> image
> 
> Error path:
> image

**Comment by kuojianlu** [comment]
> > Happy path:
> > image
> > Error path:
> > image
> 
> One question about the progress UX - is it possible to merge all preview steps into one progress? So that user can know how many remaining steps. E.g.,
> 
> ```
> [TeamsfxCLI] Preview [0/10]: Starting preview
> [TeamsfxCLI] Preview [1/10]: NPM install tabs
> [TeamsfxCLI] Preview [2/10]: NPM install api
> [TeamsfxCLI] Preview [3/10]: AAD
> ...
> ```

One question is that some steps run in parallel. For example,  since`NPM install` and `NPM install api` run in parallel, what is the UX of these two steps?
```
[TeamsfxCLI] Preview [0/10]: Starting preview
[TeamsfxCLI] Preview [1/10]: NPM install tabs
[TeamsfxCLI] Preview [2/10]: NPM install api
```
This UX means that `NPM install tabs` is done and `NPM install api` is running.

**Comment by swatDong** [comment]
I see... the same for multiple plugins. That should be a global improvement but not for `preview` only. Ok to follow existing pattern.

**Review by swatDong — APPROVED** [review]

**Comment by kuojianlu** [comment]
> I see... the same for multiple plugins. That should be a global improvement but not for `preview` only. Ok to follow existing pattern.

For multiple plugins, each plugin stage has its own title, so it is possible to have a nice UX.

**Pull request merged**
