### PR TITLE
fix(pre-auth): pre-auth office and outlook

### PR DESCRIPTION
**Pull request by kuojianlu**
- pre-auth office web client
- pre-auth outlook web and desktop client

### CODE REVIEW

**Review by swatDong — APPROVED** [review]

**Review by KennethBWSong — APPROVED** [review]

**Review by SLdragon — APPROVED** [review]

**Comment by blackchoey** [comment]
Will we enable all platforms (Teams/Outlook/Office) when user creates a new project? Or we will let users choose which platform to support?

**Comment by kuojianlu** [comment]
> Will we enable all platforms (Teams/Outlook/Office) when user creates a new project? Or we will let users choose which platform to support?

Currently, pre-auth happens on provision. It is not a project setting and can not be customized.
This PR is to add Outlook and Office pre-auth for every TeamsFx project. The scaffolding behavior is not changed.
However, pre-auth customization can be discussed afterwards if needed.

**Review by blackchoey — APPROVED** [review]

**Comment by blackchoey** [comment]
> > Will we enable all platforms (Teams/Outlook/Office) when user creates a new project? Or we will let users choose which platform to support?
> 
> Currently, pre-auth happens on provision. It is not a project setting and can not be customized. This PR is to add Outlook and Office pre-auth for every TeamsFx project. The scaffolding behavior is not changed. However, pre-auth customization can be discussed afterwards if needed.

Thanks. Please kindly notice that generate ARM template is also part of scaffolding, so the newly created project is scaffolded with all platform supported.

**Comment by kuojianlu** [comment]
> > > Will we enable all platforms (Teams/Outlook/Office) when user creates a new project? Or we will let users choose which platform to support?
> > 
> > 
> > Currently, pre-auth happens on provision. It is not a project setting and can not be customized. This PR is to add Outlook and Office pre-auth for every TeamsFx project. The scaffolding behavior is not changed. However, pre-auth customization can be discussed afterwards if needed.
> 
> Thanks. Please kindly notice that generate ARM template is also part of scaffolding, so the newly created project is scaffolded with all platform supported.

Thanks for your kind reminder. This is very important to know that.

**Pull request merged**
