### PR TITLE
refactor(solution): scaffold v2

### PR DESCRIPTION
**Pull request by 1yefuwang1**
This PR implements provisionResource for solution and changes package() implementation to using executeUserTask()`. Closes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-9.1?workitem=10644999

### CODE REVIEW

**Review by jayzhang — APPROVED** [review]

**Review by hund030 — APPROVED** [review]
Seems only code style changed in function plugin.

**Review by henzhang-ms — APPROVED** [review]
looks good to me on function plugin change

**Review by kuojianlu — APPROVED** [review]
Approve for the format style changes on local debug part.

**Review by xzf0587 — APPROVED** [review]
approve for SQL and identity

**Review by KennethBWSong — APPROVED** [review]

**Review by dooriya — APPROVED** [review]
Approve for creating default env when scaffold

**Review by IvanJobs — APPROVED** [review]
lgtm

**Pull request merged**
