### PR TITLE
feat: prepare notification dotnet template

### PR DESCRIPTION
**Pull request by swatDong**
Prepare notification dotnet project template.

E2E TEST: N/A (integration not started)

### CODE REVIEW

**Comment by yukun-dong** [comment]
could this template's name be consistent with js/ts template' name, using name "notification-restify"?

**Review by yukun-dong — COMMENTED** [review]
could this template's name be consistent with js/ts templates' name, using name "notification-restify"?

**Comment by swatDong** [comment]
> could this template's name be consistent with js/ts templates' name, using name "notification-restify"?

In .NET we directly leverage ASP.NET Core Web API for hosting, so called `webapi` instead of `restify`. Offline discussed with @hund030 for this naming during bot plugin refactoring.

**Comment by hund030** [comment]
https://github.com/OfficeDev/TeamsFx/blob/dev/templates/package.json#L11
Add `bot/csharp/notification-webapi` to the whitelist when you think the template is ready for release.

**Review by JerryYangKai — APPROVED** [review]
All looks good to me. Just a reminder, update the getstarted.txt for this template.

**Comment by swatDong** [comment]
> https://github.com/OfficeDev/TeamsFx/blob/dev/templates/package.json#L11 Add `bot/csharp/notification-webapi` to the whitelist when you think the template is ready for release.

Thanks for reminding! Yep, this PR is place-holder and there are pending changes. Will update package.json later.

**Comment by swatDong** [comment]
> All looks good to me. Just a reminder, update the getstarted.txt for this template.

Sure. I've updated a bit for bot scenario, will polish more for notification in later PRs.

**Review by dooriya — APPROVED** [review]

**Review by yukun-dong — APPROVED** [review]

**Pull request merged**
