### PR TITLE
chore(v3):  improve api for azure resource plugin

### PR DESCRIPTION
**Pull request by jayzhang**

### CODE REVIEW

**Review by HuihuiWu-Microsoft — APPROVED** [review]

**Comment by jayzhang** [comment]
API split according to Tim's suggestion:
addFeature ====> addInstance + generateCode + generateBicep
afterOtherFeaturesAdded ====> updateCode, updateBicep

**Review by XiaofuHuang — APPROVED** [review]
Approved for apim

**Review by nliu-ms — APPROVED** [review]

**Review by KennethBWSong — APPROVED** [review]
Approve for AAD

**Review by xzf0587 — APPROVED** [review]

**Review by hund030 — APPROVED** [review]

**Review by IvanJobs — APPROVED** [review]
lgtm

**Pull request merged**
