### PR TITLE
fix(local debug): remove unused localsettings fields

### PR DESCRIPTION
**Pull request by swatDong**
Fix [ADO-13083857](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13083857/)

Remove unused sql related settings from `localSettings.json` since they should be directly set into `.env.teamsfx.local`.
Updated e2e test as well.

### CODE REVIEW

**Review by kuojianlu — DISMISSED** [review]
Any changes to samples?

**Comment by swatDong** [comment]
> Any changes to samples?

No. By default `localSettings.json` is git ignored and in samples only few bot projects have `localSettings.json` checked in.

**Comment by swatDong** [comment]
@1yefuwang1 - This has e2e test change and I've verified in action (https://github.com/OfficeDev/TeamsFx/actions/runs/1748897453)

**Comment by swatDong** [comment]
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/e4bcb645180e19d7b111cefef02f9b3fc43526e3/packages/cli/tests/e2e/solution/ScaffoldTabThenAddFunctionAndSQL.tests.ts#L17

**Review by 1yefuwang1 — APPROVED** [review]

**Review by jayzhang — APPROVED** [review]

**Review by kuojianlu — APPROVED** [review]

**Review by Alive-Fish — APPROVED** [review]

**Pull request merged**
