### PR TITLE
chore: move package service to core

### PR DESCRIPTION
**Pull request by swatDong**
Move `PackageService` from cli to core, so that it can be used by CLI/VSC/actions ...

### CODE REVIEW

**Review by wenytang-ms — APPROVED** [review]
approval for CD

**Review by kuojianlu — DISMISSED** [review]

**Comment by swatDong** [comment]
> approval for CD

@wenytang-ms, I'd like to double confirm that - the content replacement is moved from `cli` to `fx-core`. Is the CD tasks sequence still correct - the update source code file will be built into fx-core package?

**Comment by wenytang-ms** [comment]
> > approval for CD
> 
> @wenytang-ms, I'd like to double confirm that - the content replacement is moved from `cli` to `fx-core`. Is the CD tasks sequence still correct - the update source code file will be built into fx-core package?

@swatDong As long as the code changes are local and do not need to publish fx-core or cli to the registry, there is no problem with such changes.

**Review by kuojianlu — APPROVED** [review]

**Review by wenytang-ms — APPROVED** [review]
approval the CD

**Review by kuojianlu — APPROVED** [review]

**Pull request merged**
