### PR TITLE
refactor: totally remove Dialog API

### PR DESCRIPTION
**Pull request by jayzhang**

### CODE REVIEW

**Review by Alive-Fish — APPROVED** [review]
Approve for CLI part.

**Review by 1yefuwang1 — APPROVED** [review]
LGTM for solution

**Review by YitongFeng-git — APPROVED** [review]

**Review by KennethBWSong — APPROVED** [review]
Approve for aad and simple auth.

**Review by xzf0587 — APPROVED** [review]
approve for sql and identity

**Review by nliu-ms — APPROVED** [review]
Approve for VSCode extension

**Review by a1exwang — APPROVED** [review]
approve for environment checker part

**Pull request merged**
