### PR TITLE
chore(bot): add adaptive card notification sample

### PR DESCRIPTION
**Pull request by XiaofuHuang**
Add adaptive card notification sample

### CODE REVIEW

**Comment by swatDong** [comment]
Where to update sample's tag?

**Comment by HuihuiWu-Microsoft** [comment]
Is this needed for GA?

**Comment by XiaofuHuang** [comment]
> Where to update sample's tag?
Tag has been updated in PR: https://github.com/OfficeDev/TeamsFx/pull/4777

**Comment by XiaofuHuang** [comment]
> Is this needed for GA?

Yes, merged into GA branch

**Review by HuihuiWu-Microsoft — APPROVED** [review]

**Review by swatDong — APPROVED** [review]

**Review by kimizhu — APPROVED** [review]

**Pull request merged**
