### PR TITLE
chore: change AIKey in source to testing AIKey and add script for CD

### PR DESCRIPTION
**Pull request by chagong**
chore: change AIKey in source to testing AIKey and add script for CD

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10308939

### CODE REVIEW

**Comment by wenytang-ms** [comment]
could these AIKeys be checkout into code ?

**Comment by chagong** [comment]
> could these AIKeys be checkout into code ?
We could. But for CLI public key it may changed after onboarding to DataX. I just don't wanna create PRs to update those keys.

**Comment by wenytang-ms** [comment]
> > could these AIKeys be checkout into code ?
> > We could. But for CLI public key it may changed after onboarding to DataX. I just don't wanna create PRs to update those keys.

so can we commit the AI keys change into code first, and just restore these codes later ?

**Comment by wenytang-ms** [comment]
https://github.com/marketplace/actions/github-action-for-package-json-update 
this GitHub cation seems can update the AI key, so it's no need to use other script

**Comment by chagong** [comment]
> https://github.com/marketplace/actions/github-action-for-package-json-update
> this GitHub cation seems can update the AI key, so it's no need to use other script

Then let me remove that script.

**Review by 1openwindow — APPROVED** [review]

**Review by Alive-Fish — APPROVED** [review]

**Pull request merged**
