### PR TITLE
chore(core): fundamental improvement of FxCore V3

### PR DESCRIPTION
**Pull request by jayzhang**

### CODE REVIEW

**Comment by jayzhang** [comment]
E2E TEST: none

**Comment by jayzhang** [comment]
Remarks: 
1. Replace addModule/scaffold/addResource with "addFeature"
2. Refactor solution, aad, frontend v3

**Review by hund030 — APPROVED** [review]
Changes on frontend v3 looks good to me.

**Review by KennethBWSong — APPROVED** [review]
approve for aad

**Comment by jayzhang** [comment]
E2E: https://github.com/OfficeDev/TeamsFx/actions/runs/1793158756

**Review by 1yefuwang1 — APPROVED** [review]

**Review by LongOddCode — APPROVED** [review]

**Review by nliu-ms — APPROVED** [review]

**Pull request merged**
