### PR TITLE
chore(multi-env): support create environment copy

### PR DESCRIPTION
**Pull request by dooriya**
## User experience for adding environment:
1. On scaffold, a default environment "dev" will be created for user;
2. When project is scaffolded, user can user "create new environment copy" command to add a new environment.
    -  User need to provide an existing environment name to copy (by default, the new env is copied from the active environment)
    - The environment input file (`config.{env}.json` and `azure.parameters.{env}.json`) are copied from the specified env.
    
## Steps to add new env copy:
Select "+" button:
image

Provide new environment name:
image

Select an existing env to create copy (default is the active env):
image

### Follow-ups:
1. @jayzhang will help to consolidate the duplicate code and sync the behavior between v1 and v2 APIs.
2. @blackchoey will help tp modify the resource base name in bicep parameter file when copy env.
3. @blackchoey will help to remove parameter.template.json.

### CODE REVIEW

**Comment by qinezh** [comment]
I'd like to double confirm the user behavoir to create an environment copy: does user need to select the existing environment to be copied? Or the active environment will be selected directly to keep consistent with the behavoir of provision, deploy, publish?

**Comment by dooriya** [comment]
> I'd like to double confirm the user behavoir to create an environment copy: does user need to select the existing environment to be copied? Or the active environment will be selected directly to keep consistent with the behavoir of provision, deploy, publish?


@yanjiang222 What's your opinion here? For me, I would prefer explicitly show the env list to copy from, since we set the active env is the default option to copy env, user just simply press `ENTER` to use the active env.

**Comment by yanjiang222** [comment]
> > I'd like to double confirm the user behavoir to create an environment copy: does user need to select the existing environment to be copied? Or the active environment will be selected directly to keep consistent with the behavoir of provision, deploy, publish?
> 
> @yanjiang222 @jaeyonglee8687 What's your opinion here? For me, I would prefer explicitly show the env list to copy from, since we set the active env is the default option to copy env, user just simply press `ENTER` to use the active env.

Personally, the design make sense to me. User both have a way to copy from default active environment but also select from an inactive environment. This cover both scenarios! thanks!

**Review by jayzhang — APPROVED** [review]

**Review by qinezh — APPROVED** [review]

**Comment by jaeyonglee8687** [comment]
Do we want to achieve 'creating a (completely) new env' as well? If then we may need to separate the actions, duplicate or create new one.

If not, we should say 'duplicate', or 'copy from' with different icon instead of 'create new' with + icon.

**Comment by dooriya** [comment]
> Do we want to achieve 'creating a (completely) new env' as well? If then we may need to separate the actions, duplicate or create new one.
> 
> If not, we should say 'duplicate', or 'copy from' with different icon instead of 'create new' with + icon.

Each time user add an environment to his project, the toolkit will **copy the env related configuration** (e.g. bicep parameters, manifest configs, etc) from an existing environment. In this sense, we don't want to provide "creating a (completely) new env" as well, which means **a new env can always be created by copying from existing one**. 

For the command naming as well as the icon, I just reference Visual Studio for the Cloud Service environment manager. It uses "**create copy**" to add new env for the cloud service. And I'm open to any suggestion on this for better understanding from user perspective :)

image

**Pull request merged**
