### PR TITLE
chore: update build local zip, update local manifest

### PR DESCRIPTION
**Pull request by xiaolang124**
1. Support build local zip and update local manifest.
2. ```codeLens``` for publish environment need to update.

### CODE REVIEW

**Comment by dooriya** [comment]
From scenario perspective, do we really need to support publish the app which is running in a local environment?

**Comment by xiaolang124** [comment]
> From scenario perspective, do we really need to support publish the app which is running in a local environment?

Not really publish Teams, it is used for publishing in manifest file. Publish will only work for remote environments. Any additions? @HuihuiWu-Microsoft 
image

**Comment by HuihuiWu-Microsoft** [comment]
> > From scenario perspective, do we really need to support publish the app which is running in a local environment?
> 
> My bad title was wrong. Not really publish Teams, it is used for updating local manifest. Publish will only work for remote environments. Any additions? @HuihuiWu-Microsoft image

Yes, this is to align with our existing feature: user can update manifest manually to dev portal. Will not affect publish feature

**Review by HuihuiWu-Microsoft — APPROVED** [review]
LGTM

**Review by nliu-ms — APPROVED** [review]

**Pull request merged**
