### PR TITLE
feat: upgrade the dotnet-sdk projects to .NET 6

### PR DESCRIPTION
**Pull request by vnbaaij**
Update NuGet packages
Replace Newtonsoft.Json with System.Text.Json
Make all tests pass

### CODE REVIEW

**Comment by vnbaaij** [comment]
DotNet SDK CI / test needs to be upgraded to use  `dotnet-version: 6.x` in 'Setup .NET'-step

**Comment by tecton** [comment]
> DotNet SDK CI / test needs to be upgraded to use `dotnet-version: 6.x` in 'Setup .NET'-step

Hi @vnbaaij, could you please help to change this in `.github/workflows/dotnetsdk-ci.yml`? This should make the tests pass.

**Comment by vnbaaij** [comment]
> > DotNet SDK CI / test needs to be upgraded to use `dotnet-version: 6.x` in 'Setup .NET'-step
> 
> Hi @vnbaaij, could you please help to change this in `.github/workflows/dotnetsdk-ci.yml`? This should make the tests pass.

This is changed now. Also found and fixed some other issues with tests.

**Comment by tecton** [comment]
E2E TEST: only for .NET SDK

**Review by tecton — APPROVED** [review]

**Comment by tecton** [comment]
> > > DotNet SDK CI / test needs to be upgraded to use `dotnet-version: 6.x` in 'Setup .NET'-step
> > 
> > 
> > Hi @vnbaaij, could you please help to change this in `.github/workflows/dotnetsdk-ci.yml`? This should make the tests pass.
> 
> This is changed now. Also found and fixed some other issues with tests.

Thank you! The last required check is UT coverage, you can merge 'dev' branch and it should pass.

**Comment by vnbaaij** [comment]
@tecton I did a fetch upstream on my fork which merged 'OfficeDev:dev' into my fork's 'dev'. Was that what you meant?

**Comment by tecton** [comment]
> @tecton I did a fetch upstream on my fork which merged 'OfficeDev:dev' into my fork's 'dev'. Was that what you meant?

Yes, I'll merge this PR.

**Pull request merged**
