### PR TITLE
chore: add pr title checker pr action

### PR DESCRIPTION
**Pull request by wenytang-ms**

### CODE REVIEW

**Comment by wenytang-ms** [comment]
image

**Comment by wenytang-ms** [comment]
image

**Comment by blackchoey** [comment]
After merge, we may also need to make this workflow as required in GitHub project setting

**Comment by wenytang-ms** [comment]
image

**Comment by wenytang-ms** [comment]
> After merge, we may also need to make this workflow as required in GitHub project setting

@LongOddCode do you know how to let this checker be required?

**Comment by wenytang-ms** [comment]
image

**Review by LongOddCode — APPROVED** [review]

**Pull request merged**
