### PR TITLE
feat: implement new progress handler in CLI

### PR DESCRIPTION
**Pull request by Alive-Fish**
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10482621

cli-progress-demo2

When meet an error:
image

### CODE REVIEW

**Review by chagong — APPROVED** [review]

**Comment by kuojianlu** [comment]
Any images to show what it looks like now?

**Comment by Alive-Fish** [comment]
> Any images to show what it looks like now?
> Does this change have any effects on the preview command?

I have shown the effects in the descriptioin.

**Review by hund030 — APPROVED** [review]
LGTM. Seems the progress bar slows down when it's near 100%, and won't be 100% until the task really be done. Just curious what if step 1 of 3 takes too much time, would it also slows down and be 33% only when the step done?

**Review by KennethBWSong — APPROVED** [review]

**Review by chagong — APPROVED** [review]

**Review by xzf0587 — APPROVED** [review]

**Review by jayzhang — APPROVED** [review]

**Review by 1yefuwang1 — APPROVED** [review]
LGTM about changes for solution

**Review by YitongFeng-git — APPROVED** [review]

**Review by HuihuiWu-Microsoft — APPROVED** [review]
LGTM for extension part

**Review by kuojianlu — APPROVED** [review]
Synced offline. Approved for preview. I will update the use of this new progress bar in preview command later.

**Review by XiaofuHuang — APPROVED** [review]

**Comment by Alive-Fish** [comment]
E2E test complete:
image

**Pull request merged**
